import React, { useEffect, useState } from 'react';
import { Header } from '../components/Header';
import { goalService } from '../services/goal';
import { Goal } from '../types';

export const Goals: React.FC = () => {
  const [goals, setGoals] = useState<Goal[]>([]);
  const [form, setForm] = useState({ name: '', target_amount: '', current_amount: '0', target_date: new Date().toISOString().slice(0, 10), notes: '' });
  const load = () => goalService.list().then(setGoals).catch(console.error);
  useEffect(() => { load(); }, []);
  const submit = async (e: React.FormEvent) => { e.preventDefault(); await goalService.create({ ...form, target_amount: Number(form.target_amount), current_amount: Number(form.current_amount), target_date: `${form.target_date}T00:00:00`, status: 'ACTIVE' }); setForm({ ...form, name: '', target_amount: '', current_amount: '0', notes: '' }); load(); };
  const contribute = async (goal: Goal) => { const amount = Number(prompt('Contribution amount')); if (amount > 0) { await goalService.contribute(goal.id, { amount, contribution_date: new Date().toISOString(), notes: 'Manual contribution' }); load(); } };
  return <div className="min-h-screen"><Header title="Goals" subtitle="Track savings goals and contributions." /><main className="space-y-6 p-4 sm:p-6 lg:p-8"><form onSubmit={submit} className="grid gap-3 rounded-lg border bg-white p-5 shadow-sm md:grid-cols-5"><input required placeholder="Goal name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="rounded-lg border px-3 py-2" /><input required type="number" placeholder="Target" value={form.target_amount} onChange={(e) => setForm({ ...form, target_amount: e.target.value })} className="rounded-lg border px-3 py-2" /><input type="number" placeholder="Saved" value={form.current_amount} onChange={(e) => setForm({ ...form, current_amount: e.target.value })} className="rounded-lg border px-3 py-2" /><input type="date" value={form.target_date} onChange={(e) => setForm({ ...form, target_date: e.target.value })} className="rounded-lg border px-3 py-2" /><button className="rounded-lg bg-blue-600 text-white">Add Goal</button></form>{goals.length === 0 ? <Empty text="No goals yet." /> : <div className="grid gap-4">{goals.map((goal) => <div key={goal.id} className="rounded-lg border bg-white p-5 shadow-sm"><div className="flex justify-between gap-3"><div className="flex-1"><p className="font-semibold">{goal.name}</p><p className="text-sm text-slate-500">Rs. {goal.current_amount.toLocaleString('en-IN')} / Rs. {goal.target_amount.toLocaleString('en-IN')} | {goal.status}</p><div className="mt-3 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{ width: `${Math.min(goal.progress_percentage, 100)}%` }} /></div></div><div className="space-x-2"><button onClick={() => contribute(goal)} className="rounded-lg bg-emerald-600 px-3 py-2 text-sm font-semibold text-white">Contribute</button><button onClick={() => goalService.delete(goal.id).then(load)} className="rounded-lg border border-red-200 px-3 py-2 text-sm font-semibold text-red-600">Delete</button></div></div></div>)}</div>}</main></div>;
};
const Empty = ({ text }: { text: string }) => <div className="rounded-lg border border-dashed border-slate-200 bg-white p-8 text-center text-sm text-slate-500 shadow-sm">{text}</div>;
